### ISSUE TITLE
[Bug] Task cursor pagination returns 500 because TaskTracker.list_page references removed _dispatcher

### ISSUE THREAD

**Issue by yufeng201** [volcengine/OpenViking#5141]
### Description

Opening the Compile page in Web Studio fails to load the task list. The cursor-paginated tasks endpoint returns HTTP 500 because `TaskTracker.list_page()` still references the removed `_dispatcher` attribute.

### Steps to reproduce

1. Run OpenViking from commit `b5b495c9506413c848184d6c36405fa5266b5f74` (reported version: `0.4.21.dev74`).
2. Open the Compile page in Web Studio, or send an authenticated request:
   `GET /api/v1/tasks?task_type=compile&pagination=cursor&limit=30`
3. Observe HTTP 500 and the following server exception:

```text
File "openviking/server/routers/tasks.py", line 121, in list_tasks
    tasks = await tracker.list_page(...)
File "openviking/service/task_tracker.py", line 997, in list_page
    return await self._dispatcher.run(read)
AttributeError: 'TaskTracker' object has no attribute '_dispatcher'
```

### Expected behavior

The endpoint returns a cursor-paginated task list, including a successful empty response when there are no matching tasks.

### Actual behavior and impact

The endpoint returns HTTP 500 and the Compile page displays a request-failed error. The stale attribute access is unconditional in `list_page()`, so the issue affects task requests using `pagination=cursor`, not only the `compile` task type.

### Root cause

#5096 (`a681e099e0e27bec63ad888b9f06034ed6415844`) removed the `OwnerLoopDispatcher` import and `self._dispatcher` initialization, but the cursor pagination method introduced in #5098 still calls it.

The stale reference also remains in the latest main checked during investigation, `80c59f13eb1e7ad22a00db1be66465ac9ebf791d`:
https://github.com/volcengine/OpenViking/blob/80c59f13eb1e7ad22a00db1be66465ac9ebf791d/openviking/service/task_tracker.py#L997

### Independent reproduction

The following reproduces the same AttributeError without accessing storage or depending on existing tasks:

```python
import asyncio
from openviking.service.task_tracker import TaskTracker

class NoIOStore:
    async def list_page(self, *args, **kwargs):
        raise AssertionError("Unexpected storage access")

async def main():
    tracker = TaskTracker(NoIOStore())
    await tracker.list_page(
        account_id="repro",
        user_id="repro",
        limit=30,
        task_type="compile",
    )

asyncio.run(main())
```

Observed result:

```text
AttributeError: 'TaskTracker' object has no attribute '_dispatcher'
```

### Suggested fix direction

Migrate the remaining pagination call to the execution model introduced by #5096 and add regression coverage for the cursor-paginated tasks endpoint.
